services:
  - type: web
    name: fatiguered-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --timeout 120 --chdir backend --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10.12
